### ISSUE TITLE
Add retention support for backups

### ISSUE THREAD

**Issue by Ndrou** [dokku/dokku-mysql#98]
Hi,

It would be useful be able to configure a retention in days on mysql backups.

Have a good day !

**Comment by josegonzalez** [comment]
You can create a lifecycle policy for an S3 bucket [like so](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/create-lifecycle.html). Because it is a fairly complex thing to setup, I don't want to burden the codebase with it, especially when not everyone will want/need it.

Hope the above doc helps.
